### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by sarment0** [bramley/phplist-plugin-sendgrid#1]
Hi, i'm trying to install this plugin and the documentation explains that i have to put a code above the "MailSend()" function, but i just fresh installed and the class file doens't have this function...

**Comment by bramley** [comment]
Which release of phplist are you using? If it is phplist 3.3.0 then the plugin needs updating to work with that, which will remove the need to make any changes to the phplist code.
Also, is it a new installation of phplist, because there have been some serious problems upgrading to release 3.3.0.

**Comment by sarment0** [comment]
@bramley 
I tried in two different version.

3.0.6 - Gives a blank page (I had to update the code)
https://www.dropbox.com/s/ml3j9st7mi0675e/Captura%20de%20tela%202017-02-13%2018.55.31.png?dl=0

3.3.1 - No need to change the code, but it fails to send. (Where do i see the full stacktrace log?)

**Comment by bramley** [comment]
As I said, the plugin needs to be updated to work with phplist 3.3.0 or later. I will try to do that tomorrow. 

The plugin should work, with the documented code changes, on 3.2.x but I don't know about an older release such as 3.0.6. I developed the plugin last June using whatever the latest phplist version was then.
If you have upgraded from 3.0.6 to 3.3.1 then you should check the user table to see whether it has been upgraded correctly. See the user forum for several topics on problems after the upgrade, https://discuss.phplist.org/

**Comment by sarment0** [comment]
@bramley I did a fresh install, not upgrade, i have phplist running on two different servers and two different versions (3.0.6 and 3.3.1).
**I will wait your update, thank you.**

**Comment by bramley** [comment]
There is a new version of the plugin that works only with phplist 3.3.0 or later. You can upgrade on the Manage Plugins page.

**Comment by sarment0** [comment]
@bramley  I just updated right now, i'm using the version: version1.1.0+20170213

Now we are very close to work, now the **test e-mail is working**, but when i finish the campaing wizard and click do start processing queued campaigns i was with sendgrid statistics Overview
opened and the numbers didn't change, not a single request arrived at their API.

**Comment by sarment0** [comment]
@bramley Ignore the last message, it was a queue problem, i schedule a campaign in the future, not right way after i created the campaign. 
It's working perfectly.
**Thank you very much!**
